-- Restaurant Order System — Seed Data
-- Run: mysql -u root restaurant_order_db < database/seed_menu.sql

SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE order_items;
TRUNCATE TABLE orders;
TRUNCATE TABLE menu_items;
SET FOREIGN_KEY_CHECKS=1;

INSERT INTO menu_items (item_name, category, price) VALUES
('Sup Gearbox Kambing','Sup ZZ',19.00),
('Sup Kambing','Sup ZZ',20.00),
('Sup Daging','Sup ZZ',8.00),
('Sup Ayam','Sup ZZ',7.00),
('Add On (Mee/Mee Hoon/Kuey Teow)','Sup ZZ',2.00),
('Add On Set Nasi','Sup ZZ',5.00),
('Add On Roti Francis/Gardenia','Sup ZZ',2.50),
('Mee Rebus Gearbox Kambing','Mee Rebus ZZ',20.00),
('Mee Rebus Daging','Mee Rebus ZZ',9.50),
('Mee Rebus Ayam','Mee Rebus ZZ',9.00),
('Ikan Siakap Tiga Rasa','Ikan Siakap',35.00),
('Ikan Siakap Masam Manis','Ikan Siakap',35.00),
('Ikan Siakap Steam Lemon','Ikan Siakap',35.00),
('Ikan Siakap Laprik','Ikan Siakap',35.00),
('Ikan Siakap Goreng Kunyit','Ikan Siakap',35.00),
('Siakap Bakar','Bakar-Bakar',35.00),
('Caru Bakar','Bakar-Bakar',8.00),
('Kerang Bakar','Bakar-Bakar',15.00),
('Sotong Bakar','Bakar-Bakar',15.00),
('Ikan Bakar Sambal','Bakar-Bakar',15.00),
('Lontong Kuah','Masakan Panas',7.50),
('Lontong Kering (Ayam)','Masakan Panas',9.00),
('Lontong Kering (Daging)','Masakan Panas',9.50),
('Nasi Lemak Basmathi (Telur)','Masakan Panas',6.00),
('Nasi Lemak Basmathi (Ayam)','Masakan Panas',9.00),
('Nasi Lemak Rendang (Ayam)','Masakan Panas',8.50),
('Nasi Lemak Rendang (Daging)','Masakan Panas',9.50),
('Nasi Ayam Basmathi','Masakan Panas',12.00),
('Nasi Ambang','Masakan Panas',9.50),
('Bubur Nasi','Masakan Panas',7.50),
('Bubur Ayam','Masakan Panas',7.00),
('Laksa (Johor)','Masakan Panas',8.00),
('Laksa (Penang)','Masakan Panas',7.50),
('Bakso (Mee/Mee Hoon/Nasi)','Masakan Panas',7.50),
('Soto (Mee/Mee Hoon/Nasi)','Masakan Panas',8.00),
('Roti Bakar','Roti Bakar',2.50),
('Roti Kaya','Roti Bakar',3.50),
('Roti Garlic','Roti Bakar',3.50),
('Add On Telur 1/2 Masak','Roti Bakar',3.50),
('Nasi Bawal Goreng Berlado','Set Nasi & Lauk',9.00),
('Nasi Siakap Goreng Berlado','Set Nasi & Lauk',15.00),
('Nasi Keli Goreng Berlado','Set Nasi & Lauk',10.90),
('Nasi Ayam Goreng Berlado','Set Nasi & Lauk',8.50),
('Roti Kosong','Roti Canai',1.50),
('Roti Kosong Bawang','Roti Canai',2.00),
('Roti Tampal','Roti Canai',2.80),
('Roti Telur','Roti Canai',2.80),
('Roti Telur Bawang','Roti Canai',3.50),
('Roti Telur Double Jantan','Roti Canai',5.50),
('Roti Pisang','Roti Canai',4.50),
('Roti Sardin','Roti Canai',6.00),
('Roti Bom','Roti Canai',2.50),
('Roti Planta','Roti Canai',3.00),
('Roti Sarang Burung Daging','Roti Canai',8.00),
('Roti Canai','Roti Canai',1.50),
('Nasi Goreng Kampung','Nasi Goreng',8.00),
('Nasi Goreng Biasa','Nasi Goreng',7.50),
('Nasi Goreng Cina','Nasi Goreng',7.50),
('Nasi Goreng Ikan Masin','Nasi Goreng',8.50),
('Nasi Goreng Cili Padi','Nasi Goreng',8.50),
('Nasi Goreng Pattaya','Nasi Goreng',8.50),
('Nasi Goreng Tom Yam','Nasi Goreng',9.00),
('Nasi Goreng Belacan','Nasi Goreng',12.00),
('Add On Daging (Nasi Goreng)','Nasi Goreng',1.00),
('Add On Udang (Nasi Goreng)','Nasi Goreng',3.00),
('Add On Sotong (Nasi Goreng)','Nasi Goreng',3.00),
('Mee Goreng','Mee Goreng',7.50),
('Mee Hoon Goreng Singapore','Mee Goreng',7.50),
('Char Kuey Teow','Mee Goreng',8.00),
('Add On Daging (Mee Goreng)','Mee Goreng',1.00),
('Add On Udang (Mee Goreng)','Mee Goreng',3.00),
('Add On Sotong (Mee Goreng)','Mee Goreng',3.00),
('Sup Ayam Ala Thai','Sup Ala Thai',8.00),
('Sup Daging Ala Thai','Sup Ala Thai',9.00),
('Add On Mee/Mee Hoon (Sup Ala Thai)','Sup Ala Thai',2.00),
('Tom Yam Ayam','Tomyam',8.00),
('Tom Yam Daging','Tomyam',9.00),
('Tom Yam Ayam + Daging','Tomyam',12.00),
('Tom Yam Seafood','Tomyam',13.00),
('Tom Yam Campur','Tomyam',13.00),
('Tom Yam Sayur','Tomyam',8.00),
('Tom Yam Cendawan','Tomyam',8.00),
('Add On Mee/Mee Hoon (Tomyam)','Tomyam',2.00),
('Mee Kuah Bandung','Mee Kuah',10.50),
('Mee Kuah Hong Kong','Mee Kuah',10.50),
('Mee Kuah Hailam','Mee Kuah',10.50),
('Mee Kuah Kung Fu','Mee Kuah',10.50),
('Kailan (Biasa/Ikan Masin)','Sayur',7.00),
('Kangkung (Biasa/Belacan)','Sayur',7.00),
('Taugeh (Biasa/Ikan Masin)','Sayur',7.00),
('Sawi (Biasa/Ikan Masin)','Sayur',7.00),
('Cendawan Goreng Biasa','Sayur',7.00),
('Ayam Black Pepper','Aneka Lauk Thai',7.50),
('Daging Black Pepper','Aneka Lauk Thai',8.50),
('Sotong Black Pepper','Aneka Lauk Thai',9.50),
('Ayam Sambal','Aneka Lauk Thai',7.50),
('Daging Sambal','Aneka Lauk Thai',8.50),
('Sotong Sambal','Aneka Lauk Thai',9.50),
('Ayam Merah','Aneka Lauk Thai',7.50),
('Daging Merah','Aneka Lauk Thai',8.50),
('Sotong Merah','Aneka Lauk Thai',9.50),
('Ayam Paprik','Aneka Lauk Thai',7.50),
('Daging Paprik','Aneka Lauk Thai',8.50),
('Sotong Paprik','Aneka Lauk Thai',9.50),
('Ayam Pha Khra Phao','Aneka Lauk Thai',8.00),
('Daging Pha Khra Phao','Aneka Lauk Thai',9.00),
('Ayam Kunyit','Aneka Lauk Thai',7.50),
('Daging Kunyit','Aneka Lauk Thai',9.50),
('Sotong Kunyit','Aneka Lauk Thai',9.50),
('Udang Kunyit','Aneka Lauk Thai',9.50),
('Add On Nasi Putih (Lauk Thai)','Aneka Lauk Thai',2.00),
('Add On Nasi Goreng (Lauk Thai)','Aneka Lauk Thai',3.00),
('Goreng Tepung Sotong','Goreng Tepung',10.50),
('Goreng Tepung Udang','Goreng Tepung',10.50),
('Goreng Tepung Cendawan','Goreng Tepung',7.00),
('Goreng Tepung Inokki','Goreng Tepung',7.00),
('Chicken Chop (Fried/Grill)','Fried & Grill',18.50),
('Fish N Chips','Fried & Grill',16.50),
('Lamb Chop','Fried & Grill',30.90),
('Aglio Olio (Chicken)','Spaghetti',13.00),
('Aglio Olio (Beef Bacon)','Spaghetti',15.00),
('Aglio Olio (Seafood)','Spaghetti',17.00),
('Carbonara (Chicken)','Spaghetti',14.00),
('Carbonara (Beef Bacon)','Spaghetti',16.00),
('Carbonara (Seafood)','Spaghetti',18.00),
('Bolognese','Spaghetti',15.00),
('Mac & Cheese','Spaghetti',12.00),
('Smash Beef Single','Burger',8.00),
('Smash Beef Double','Burger',10.00),
('Crispy Chicken Burger','Burger',7.50),
('Add On Fries (Burger)','Burger',2.00),
('Fries','Sides',7.50),
('Nugget 8pcs','Sides',8.00),
('Cheesy Wedges','Sides',8.50),
('Teh Tarik','Non-Coffee',2.50),
('Teh O','Non-Coffee',2.30),
('Teh Halia','Non-Coffee',3.50),
('Teh Sarbat','Non-Coffee',3.50),
('Sirap','Non-Coffee',2.00),
('Sirap Selasih','Non-Coffee',2.50),
('Sirap Limau','Non-Coffee',2.70),
('Sirap Laici','Non-Coffee',5.00),
('Sirap Bandung (Iced)','Non-Coffee',3.50),
('Sirap Bandung Cincau (Iced)','Non-Coffee',4.00),
('Sirap Bandung Soda (Iced)','Non-Coffee',4.00),
('Limau','Non-Coffee',2.70),
('Asam Boy','Non-Coffee',2.70),
('Extra Joss Susu (Iced)','Non-Coffee',4.00),
('Vico','Non-Coffee',3.00),
('Indo Cafe O','Coffee',3.00),
('Indo Cafe Susu','Coffee',3.50),
('Kopi Tenggek','Coffee',3.50),
('Kopi Special','Coffee',4.00),
('Jus Oren','Jus',5.00),
('Jus Epal','Jus',5.00),
('Jus Tembikai','Jus',5.00),
('Jus Laici','Jus',5.00),
('Jus Lemon','Jus',5.00),
('Cikong','Cold Dessert',6.00),
('Ais Jelly Limau','Cold Dessert',6.00),
('Cendol','Cold Dessert',6.00),
('Es Kacang','Cold Dessert',5.00),
('Ayam Goreng Berempah','Lain-Lain',12.00);

-- Sample orders for testing manage_orders.php
INSERT INTO orders (customer_name, phone, order_type, table_no, total_amount, order_status, order_date) VALUES
('Table 4 (Walk-In)',  '0123456789', 'Walk-In',  '4',  27.00,  'Pending',    NOW()),
('Ali Ahmad (Online)', '0198765432', 'Online',   NULL, 23.00,  'In Progress',NOW()),
('Table 7 (Walk-In)',  '0112223333', 'Walk-In',  '7',  11.50,  'Ready',      NOW()),
('Table 2 (Walk-In)',  '0134445555', 'Walk-In',  '2',  13.00,  'Completed',  NOW()),
('Siti (Online)',      '0156667777', 'Online',   NULL, 29.00,  'Completed',  NOW() - INTERVAL 1 HOUR),
('Table 5 (Walk-In)',  '0178889999', 'Walk-In',  '5',  16.00,  'Pending',    NOW() - INTERVAL 1 DAY),
('Rahman (Online)',    '0190001111', 'Online',   NULL, 32.50,  'Completed',  NOW() - INTERVAL 1 DAY);

-- Sample order items (uses item_id from menu_items, first 4 orders are today)
-- Order 1: Walk-in Table 4 — Pending
INSERT INTO order_items (order_id, item_id, quantity, subtotal, status) VALUES
(1, 1, 1, 19.00, 'Pending'),
(1, 10, 1, 9.00, 'Pending');

-- Order 2: Online Ali — In Progress
INSERT INTO order_items (order_id, item_id, quantity, subtotal, status) VALUES
(2, 56, 2, 5.00, 'In Progress'),
(2, 57, 2, 16.00, 'In Progress');

-- Order 3: Walk-in Table 7 — Ready
INSERT INTO order_items (order_id, item_id, quantity, subtotal, status) VALUES
(3, 56, 3, 7.50, 'Ready'),
(3, 44, 1, 1.50, 'Ready');

-- Order 4: Walk-in Table 2 — Completed
INSERT INTO order_items (order_id, item_id, quantity, subtotal, status) VALUES
(4, 4, 1, 7.00, 'Completed'),
(4, 36, 2, 5.00, 'Completed');

-- Order 5: Online Siti — Completed
INSERT INTO order_items (order_id, item_id, quantity, subtotal, status) VALUES
(5, 163, 1, 12.00, 'Completed'),
(5, 160, 2, 10.00, 'Completed');

